refactor(input-range): Realize two-way binding of v-model
hug-sun-1/element3 pull request #12
Opened 2021-03-13 08:21 UTC by zqy1151215064

实现InputRange v-model 双向绑定

2021-03-13 10:19 UTC, WumaCoder commented
hug-sun#579

2021-03-13 10:30 UTC, WumaCoder requested changes
如何确保样式

2021-03-13 10:30 UTC, WumaCoder commented on packages/element3/src/components/InputRange/src/InputRange.vue
> +    <input :value="modelValue && modelValue[1]" @input="handleEndInput" />
这里不需要判断是否有modelValue变量，直接采用后面的写法就行

2021-03-13 10:30 UTC, WumaCoder commented on packages/element3/src/components/InputRange/src/InputRange.vue
> +    const handleEntInput = function (event: { target: { value: any } }) {
handleEndInput名字错误

2021-03-13 10:30 UTC, WumaCoder commented on packages/element3/src/components/InputRange/src/InputRange.vue
> +    })
这块想要实现什么功能

2021-03-15 02:43 UTC, merged

2021-03-15 02:46 UTC, zqy1151215064 commented on packages/element3/src/components/InputRange/src/InputRange.vue
> +    <input :value="modelValue && modelValue[1]" @input="handleEndInput" />
数组为[] , 不确定 会不会直接赋值 undefined

2021-03-15 02:47 UTC, zqy1151215064 commented on packages/element3/src/components/InputRange/src/InputRange.vue
> +    const handleEntInput = function (event: { target: { value: any } }) {
已修改

2021-03-15 02:47 UTC, zqy1151215064 commented on packages/element3/src/components/InputRange/src/InputRange.vue
> +    })
再想这组件内部，需不需要保存一个自己的modelvalue值

2021-03-15 02:56 UTC, WumaCoder commented on packages/element3/src/components/InputRange/src/InputRange.vue
> +    })
不需要有自己的modelValue，只要不绑定变量就不能修改

2021-03-15 02:57 UTC, WumaCoder commented on packages/element3/src/components/InputRange/src/InputRange.vue
> +    <input :value="modelValue && modelValue[1]" @input="handleEndInput" />
就当他是必须要传的参数就行

2021-03-15 02:58 UTC, zqy1151215064 commented on packages/element3/src/components/InputRange/src/InputRange.vue
> +    <input :value="modelValue && modelValue[1]" @input="handleEndInput" />
[] 好像也是当做传了参数的呀

2021-03-15 03:11 UTC, WumaCoder commented on packages/element3/src/components/InputRange/src/InputRange.vue
> +    <input :value="modelValue && modelValue[1]" @input="handleEndInput" />
要不直接在prop的那个验证回调里写一个验证就行

2021-03-15 03:15 UTC, WumaCoder commented on packages/element3/src/components/InputRange/src/InputRange.vue
> +    <input :value="modelValue && modelValue[1]" @input="handleEndInput" />
或者不写也行就当，我们传人的就是你想的，文档写清楚就行